version: '3.8'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-init:/docker-entrypoint-initdb.d/
    networks:
      - default

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-nestjs
    restart: unless-stopped
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - default

volumes:
  mysql-volume:

networks:
  default: